name: moca_flutter
description: Flutter plugin for Moca SDK. Moca is an enterprise geofencing platform for apps.
version: 3.0.0
homepage: https://github.com/innoquant/moca-flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.moca.flutter
        pluginClass: MocaFlutterPlugin
      ios:
        pluginClass: MocaFlutterPlugin
